server:
  port: 8090
spring:
  datasource:
    driverClassName: org.h2.Driver
    initialization-mode: never
    password: ''
    url: jdbc:h2:mem:mytestdb
    username: sa
  h2:
    console:
      enabled: true
      path: /h2-console
  jackson:
    time-zone: America/Guayaquil
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
springdoc:
  swagger-ui:
    path: /api-doc.html